FROM vincinator/bp:live
MAINTAINER Vincent Riesop (Vincent.Riesop@yahoo.com)

RUN apt-get update --fix-missing && apt-get install -y postgresql-9.5 postgresql-contrib-9.5 postgresql-9.5-postgis-2.2 sudo default-jre tomcat8 wget vim osmosis

# Clean old ROOT.war if already exists
RUN sudo rm -f /opt/ROOT.war
RUN sudo rm -f /opt/install.sh
RUN sudo rm -f /opt/ExportTool.jar

COPY install.sh /opt/
COPY ROOT.war /opt/ROOT.war
COPY Darmstadt.osm.pbf /opt/
COPY ExportTool.jar /opt/

RUN service postgresql start && \
            service postgresql start && \
            #su postgres -c "createdb hibernatedb --owner postgres"  && \
            #sudo -u postgres psql -U postgres -d postgres -c "alter user postgres with password 'password';" && \
            sudo rm -rf /var/lib/tomcat8/webapps/ROOT && \
            sudo cp /opt/ROOT.war /var/lib/tomcat8/webapps/ && \
            sudo chown tomcat8:tomcat8 /var/lib/tomcat8/webapps/ROOT.war && \
Creating OSM Database
            su postgres -c "createdb osm --owner postgres"  && \
            sudo -u postgres psql -U postgres -d osm -c 'CREATE EXTENSION postgis; CREATE EXTENSION hstore;' && \
            sudo -u postgres psql -U postgres -d osm -f /usr/share/doc/osmosis/examples/pgsnapshot_schema_0.6.sql && \
            sudo -u postgres psql -U postgres -d osm -f /usr/share/doc/osmosis/examples/pgsnapshot_schema_0.6.sql && \
            osmosis --read-pbf /opt/Darmstadt.osm.pbf --log-progress --write-pgsql database=osm user="postgres" password="password" && \

            service postgresql stop



EXPOSE 8080
