FROM vincinator/bp:latest
MAINTAINER Vincent Riesop (Vincent.Riesop@yahoo.com)
RUN apt-get update
RUN apt-get install -y postgresql-9.5 postgresql-contrib-9.5 sudo default-jre tomcat8 wget vim

COPY install.sh /opt/
COPY ROOT.war /opt/ROOT.war
RUN sh /opt/install.sh
